#
# Makefile
#
# Computer 50
# evo1 project test
# 

all: test

test: test.c ndice.c ndice.h
	gcc -ggdb3 -O0 -std=c11 -Wall -Werror -o test test.c ndice.c

#clean:
#    rm -f *.o a.out core find generate
